# Site settings
title: JadeWu Blog
SEOTitle: 伍文婕的博客 | Jade Wu Blog
header-img: img/home-bg-o.jpg
email: ww2159@nyu.edu.com
description: "A Software Developer | Code change the world."
keyword: "JadeWu Blog, Jade Wu, Jadeww, Wenjie Wu, Jade Wenjie Wu Blog"
url: "http://jadeww.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jadeww/jadeww.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "MSc in Computer Engineering @NYU"
sidebar-avatar: /img/avatar-jade.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    jadeww
# facebook_username:  jadeww
linkedin_username:  firstname-lastname-idxxxx
# twitter_username:   jadeww




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
 


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
# plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 51ffcd670083269cfed3                            #生成的clientID
  clientSecret: 833e8ad24732f415b6f48b95442938e957d76cf7    #生成的clientSecret
  repo: jadeww.github.io    #仓库名称
  owner: jadeww    #github用户名
  admin: jadeww
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
